version: "3.7"
services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  web:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - mosquitto
